# Generated by Django 6.0.3 on 2026-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_desc_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
    ]
