# Generated by Django 6.0.3 on 2026-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_address_profile_encrypted_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='encrypted_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
