# Generated by Django 6.0.3 on 2026-03-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
