# Generated by Django 6.0.3 on 2026-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
