# Generated by Django 6.0.3 on 2026-05-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_time',
            field=models.IntegerField(default=0, help_text='Phút'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(default=0, help_text='Phút'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_histories', to='tasks.status')),
                ('old_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_histories', to='tasks.status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_taskhistory',
            },
        ),
    ]
