# Generated by Django 6.0.3 on 2026-05-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_actual_time_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#5b67f7', max_length=20, verbose_name='Màu nhãn'),
        ),
    ]
