# Generated by Django 6.0.3 on 2026-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#94a3b8', max_length=20, verbose_name='Màu nhãn'),
        ),
    ]
